### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by ily666666** [Charleshhy/One-shot-Human-Parsing#1]
这数据集是你们自己创建并标注的吗？

**Comment by Charleshhy** [comment]
Hi,

The ATR-OS dataset is tailored into the one-shot learning settings from the existing large-scale human parsing dataset ATR. The tailoring method is described in https://arxiv.org/abs/2012.11810 dataset section.

We also tailored two more challenging human parsing datasets into the OSHP settings, which is described in https://arxiv.org/abs/2105.01241 . We hope we can release the code for both repositories including the datasets in late next week.

Kind regards,
Haoyu
