### ISSUE TITLE
size mismatch for prototype

### ISSUE THREAD

**Issue by xddlj** [Charleshhy/One-shot-Human-Parsing#10]
bash scripts/evaluate_atr_kwf1.sh

the content of evaluate_atr_kwf1.sh：
      export PYTHONPATH="${PYTHONPATH}:$(pwd)"
      python ./exp/train.py \
       --batch 2 \
       --gpus 1 \
       --resume_model ./data/pretrained_model/atr_kwf1.pth \
       --resume_epoch 39 \
       --lr 0.001 \
       --numworker 6 \
       --testInterval 10 \
       --hidden_layers 256 \
       --epochs 50 \
       --dataset atr \
       --test_classes 18 \
       --fold 1 \
       --way 'kway' \
       --structure kway_oshp \
       --size 512 \
       --prototype_warmup 25 \
       --fg_weight 1.0 \
       --contrast_weight 1.0 \
       --testing_screening \
       --feature_lvl mid \
       --temperature 0.1 \
       --validate

result:
    => Structure:kway_oshp, dataset:atr, way:kway, fold:1
    => Saving log to: /home/fuzhi-dlj/workspace_big_bang/workspace/infant/human_parse/One-shot-Human-Parsing/exp/run_cihp/run_6
    Constructing DeepLabv3+ model...
    Output stride: 16
    Number of Input Channels: 3
    => No model load!
    opts.resume_model ./data/pretrained_model/atr_kwf1.pth
    Traceback (most recent call last):
      File "./exp/train.py", line 560, in <module>
        main(opts)
      File "./exp/train.py", line 381, in main
        net_.load_state_dict(x)
      File "/home/fuzhi-dlj/workspace/conda_list/pyt1736/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
        self.__class__.__name__, "\n\t".join(error_msgs)))
    RuntimeError: Error(s) in loading state_dict for EOPNet_kway:
	    size mismatch for prototype: copying a param with shape torch.Size([20, 256]) from checkpoint, the shape in current model is torch.Size([18, 256]).

**Comment by ZiAngGu1** [comment]
reproduce the same error
have you solved this question?

**Comment by Charleshhy** [comment]
Hi guys, 

I am terribly sorry for getting back to you this late as I lost access to the server that stores the previous checkpoints and was busy with other projects. I managed to get the correct checkpoint today and uploaded it in the [drive folder](https://drive.google.com/drive/folders/1qn-dyxmpn6F7FmPrtVl2duDPTtSUjEWF?usp=sharing). 

Please don't hesitate to contact me if you meet other bugs or difficulties.

Kind regards,
Haoyu

**Comment by ZiAngGu1** [comment]
Dear Haoyu,
Thanks for your attention on the question posted.
Have a nice day!
Sincerely,
ZiAng
________________________________
发件人: Charleshhy ***@***.***>
发送时间: 2023年2月1日 1:05
收件人: Charleshhy/One-shot-Human-Parsing ***@***.***>
抄送: Gu, Ziang ***@***.***>; Comment ***@***.***>
主题: Re: [Charleshhy/One-shot-Human-Parsing] size mismatch for prototype (Issue #10)


Hi guys,

I am terribly sorry for getting back to you this late as I lost access to the server of the previous checkpoints and was busy with other projects. I managed to get the correct checkpoint today and uploaded it in the drive folder<https://urldefense.com/v3/__https://drive.google.com/drive/folders/1qn-dyxmpn6F7FmPrtVl2duDPTtSUjEWF?usp=sharing__;!!HXCxUKc!xFyyw2zhy2bxU2CDGt5kxCBk-68Mt7Lu7ShRsy0iRg-aZ1mjPKM9hpeDbuRYiFmtqM6CNRZh7xUeKp1KUUewMC3D$>.

Please don't hesitate to contact me if you meet other bugs or difficulties.

Kind regards,
Haoyu

―
