### ISSUE TITLE
how long is spend to predict a image 

### ISSUE THREAD

**Issue by yier2333** [Charleshhy/One-shot-Human-Parsing#11]

**Comment by Charleshhy** [comment]
Hi yier2333,

Sorry for getting back so late and thanks for your interest in our project! Please refer to Table 5 in our [original paper](https://arxiv.org/abs/2105.01241) that the FPS for EOP-Net is 12.0 on a single NVIDIA Tesla V100 GPU.

Kind regards,
Haoyu
