### ISSUE TITLE
Data sets usage license

### ISSUE THREAD

**Issue by AlkaSaliss** [Charleshhy/One-shot-Human-Parsing#5]
Hello 
Thanks for the awesome work

In the README, there are link to datasets that can be downloaded via google drive, can you specify what are the licenses for using these datasets

b.r

**Comment by Charleshhy** [comment]
Hi AlkaSaliss,

Thanks for your interest in our project! The datasets are published in [this](https://github.com/Gaoyiminggithub/Graphonomy) repository by Sun Yat-sen University, which is of MIT license. I believe these three datasets are not under any limits for research purpose, however, you might have to enquiry Sun Yat-sen University (owner of [this](https://github.com/Gaoyiminggithub/Graphonomy) repo) for commercial usages.

Kind regards,
Haoyu

**Comment by AlkaSaliss** [comment]
Thanks for the very quick reply and for the pointers, will check that
