### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by dandanAD** [Charleshhy/One-shot-Human-Parsing#7]
Hello, I am running the project recently. I hope you can provide it. Please pass the application. My account number is varitkohl419@gmail.com Thank you very much.

**Comment by Charleshhy** [comment]
Hi,

I have detailed how to build one-shot datasets in the data preparation section in [README.md](https://github.com/Charleshhy/One-shot-Human-Parsing/blob/main/README.md). The process is a little bit tedious but I am happy to help you if you encounter any difficulties. We are also considering optimizing the code and dataset construction process after the revision of our paper (which might be finished by the end of next month) :)

Kind regards,
Haoyu
