### ISSUE TITLE
example of inference

### ISSUE THREAD

**Issue by xddlj** [Charleshhy/One-shot-Human-Parsing#9]
Can you provide a simply script to get the visualization result？ thanks you！

**Comment by Charleshhy** [comment]
Hi xddlj,

Thanks for your interest in our project! Please see the visualization code from [line 383](https://github.com/Charleshhy/One-shot-Human-Parsing/blob/2ed721b2c1a560f077a8dda28b271853ce430c3b/utils/util.py#L383) to [line 415](https://github.com/Charleshhy/One-shot-Human-Parsing/blob/2ed721b2c1a560f077a8dda28b271853ce430c3b/utils/util.py#L415). 

Kind regards,
Haoyu

**Comment by xddlj** [comment]
> Hi xddlj,
> 
> Thanks for your interest in our project! Please see the visualization code from [line 383](https://github.com/Charleshhy/One-shot-Human-Parsing/blob/2ed721b2c1a560f077a8dda28b271853ce430c3b/utils/util.py#L383) to [line 415](https://github.com/Charleshhy/One-shot-Human-Parsing/blob/2ed721b2c1a560f077a8dda28b271853ce430c3b/utils/util.py#L415).
> 
> Kind regards, Haoyu

Great！ thanks
